# Generated by Django 2.2.2 on 2019-12-08 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('result', models.IntegerField(blank=True, default=0, null=True)),
                ('error', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Incompleta', 'Incompleta'), ('Ejecutándose', 'Ejecutándose'), ('Terminada', 'Terminada'), ('Terminada debido a un error', 'Terminada debido a un error')], default='Pendiente', max_length=30, null=True)),
                ('type', models.CharField(choices=[('Crawler', 'Crawler')], default='', max_length=23)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at', 'state'],
            },
        ),
    ]
