# Generated by Django 3.0.5 on 2020-05-20 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='nombre')),
                ('state', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Incompleta', 'Incompleta'), ('Ejecutándose', 'Ejecutándose'), ('Terminada', 'Terminada'), ('Terminada debido a un error', 'Terminada debido a un error')], default='Pendiente', max_length=30, null=True, verbose_name='estado')),
                ('type', models.CharField(choices=[('Crawler', 'Crawler')], default='', max_length=23, verbose_name='tipo')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='descripción')),
                ('result', models.IntegerField(blank=True, default=0, null=True, verbose_name='resultado')),
                ('error', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='error')),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='fecha de comienzo de la tarea')),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='fecha de finalización de la tarea')),
                ('created_at', models.DateTimeField(editable=False, null=True, verbose_name='fecha de creación del registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de actualización del registro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at', 'state'],
            },
        ),
    ]
