# Generated by Django 3.0.5 on 2020-05-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Crawler', 'Crawler')], default='', max_length=23, null=True, verbose_name='tipo'),
        ),
    ]
