# Generated by Django 2.2.2 on 2020-05-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.CharField(max_length=200, verbose_name='error'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Incompleta', 'Incompleta'), ('Ejecutándose', 'Ejecutándose'), ('Terminada', 'Terminada'), ('Terminada debido a un error', 'Terminada debido a un error')], default='Pendiente', max_length=30, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Crawler', 'Crawler')], default='', max_length=23, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
