# Generated by Django 2.2.2 on 2020-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200502_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de actualización del registro'),
        ),
    ]
