# Generated by Django 2.2.2 on 2019-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Ejecutándose', 'Ejecutándose'), ('Terminada', 'Terminada'), ('Terminada debido a un error', 'Terminada debido a un error')], default='Pendiente', max_length=30, null=True),
        ),
    ]
