# Generated by Django 2.2.2 on 2019-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191201_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
