# Generated by Django 2.2.2 on 2019-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Incompleta', 'Incompleta'), ('Ejecutándose', 'Ejecutándose'), ('Terminada', 'Terminada'), ('Terminada debido a un error', 'Terminada debido a un error')], default='Pendiente', max_length=30, null=True),
        ),
    ]
