# Generated by Django 2.2.2 on 2019-11-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='country',
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalJob',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('state', models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Actualizada', 'Actualizada'), ('Inscripción cerrada', 'Inscripción cerrada')], default='', max_length=20, null=True)),
                ('type', models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo nacional'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=23)),
                ('summary', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, null=True, size=6)),
                ('_experience', models.CharField(blank=True, max_length=40, null=True)),
                ('_salary', models.CharField(blank=True, max_length=40, null=True)),
                ('_contract', models.CharField(blank=True, max_length=30, null=True)),
                ('_working_day', models.CharField(blank=True, max_length=30, null=True)),
                ('minimum_years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('recommendable_years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('minimum_salary', models.IntegerField(blank=True, null=True)),
                ('maximum_salary', models.IntegerField(blank=True, null=True)),
                ('working_day', models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'indiferente'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], max_length=23)),
                ('contract', models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], max_length=32)),
                ('cityname', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, null=True, size=6)),
                ('provincename', models.CharField(blank=True, max_length=100, null=True)),
                ('countryname', models.CharField(max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('registered_people', models.IntegerField(default=0)),
                ('first_publication_date', models.DateField(blank=True, default=None, null=True)),
                ('last_update_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('it_is_offered', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('Educación, formación', 'Educación, formación'), ('Tecnología e informática', 'Tecnología e informática'), ('Sanidad, salud y servicios sociales', 'Sanidad, salud y servicios sociales'), ('Medios, editorial y artes gráficas', 'Medios, editorial y artes gráficas'), ('Compras, logística y transporte', 'Compras, logística y transporte'), ('Administrativos y secretariado', 'Administrativos y secretariado'), ('Profesionales, artes y oficios', 'Profesionales, artes y oficios'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Legal', 'Legal'), ('Internet', 'Internet'), ('Banca y seguros', 'Banca y seguros'), ('Calidad, I+D, PRL y medio ambiente', 'Calidad, I+D, PRL y medio ambiente'), ('Recursos humanos', 'Recursos humanos'), ('Comercial, ventas', 'Comercial, ventas'), ('Ingeniería y producción', 'Ingeniería y producción'), ('Atención al cliente', 'Atención al cliente'), ('Construcción e inmobiliaria', 'Construcción e inmobiliaria'), ('Hostelería, Turismo', 'Hostelería, Turismo'), ('Administración de Empresas', 'Administración de Empresas'), ('Marketing y comunicación', 'Marketing y comunicación')], max_length=34)),
                ('category_level', models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], max_length=15)),
                ('vacancies', models.IntegerField()),
                ('vacancies_update', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Job',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('company_link', models.URLField(null=True)),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('company_description', models.TextField(null=True)),
                ('company_city_name', models.CharField(max_length=50, null=True)),
                ('company_category', models.CharField(max_length=100, null=True)),
                ('company_offers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.City')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
