# Generated by Django 3.0.5 on 2020-05-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_cities',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_contract',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_country',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_experience',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_province',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_salary',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='_working_day',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_cities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_contract',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_province',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_working_day',
        ),
    ]
