# Generated by Django 2.2.2 on 2019-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
