# Generated by Django 3.0.5 on 2020-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200524_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljob',
            name='vacancies_update',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancies_update',
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='type',
            field=models.CharField(default='Trabajo en el extranjero', max_length=30, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default='Trabajo en el extranjero', max_length=30, verbose_name='tipo'),
        ),
    ]
