# Generated by Django 2.2.2 on 2020-04-01 14:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200219_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area',
            field=django_mysql.models.ListCharField(models.CharField(max_length=45), blank=True, max_length=1570, null=True, size=34),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='area',
            field=django_mysql.models.ListCharField(models.CharField(max_length=45), blank=True, max_length=1570, null=True, size=34),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('inglés', 'inglés'), ('francés', 'francés'), ('alemán', 'alemán'), ('italiano', 'italiano'), ('ruso', 'ruso'), ('chino', 'chino'), ('japonés', 'japonés'), ('canadiense', 'canadiense'), ('portugués', 'portugués'), ('euskera', 'euskera'), ('catalán', 'catalán'), ('gallego', 'gallego'), ('vasco', 'vasco'), ('valenciano', 'valenciano'), ('castellano', 'castellano'), ('español', 'español'), ('danés', 'danés'), ('sueco', 'sueco'), ('suizo', 'suizo'), ('holandés', 'holandés'), ('noruego', 'noruego'), ('finés', 'finés'), ('lapón', 'lapón'), ('rumano', 'rumano'), ('polaco', 'polaco'), ('eslovaco', 'eslovaco'), ('checo', 'checo'), ('maltés', 'maltés'), ('árabe', 'árabe')], default='', max_length=15),
        ),
    ]
