# Generated by Django 2.2.2 on 2019-11-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20191113_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljob',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
        migrations.DeleteModel(
            name='HistoricalJob',
        ),
    ]
