# Generated by Django 3.0.5 on 2020-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200526_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='type',
            field=models.CharField(choices=[('Trabajo en el extranjero', 'Empleo internacional'), ('Trabajo', 'Empleo nacional'), ('Primer trabajo y practicas', 'Primer empleo')], default='Trabajo', max_length=30, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Trabajo en el extranjero', 'Empleo internacional'), ('Trabajo', 'Empleo nacional'), ('Primer trabajo y practicas', 'Primer empleo')], default='Trabajo', max_length=30, verbose_name='tipo'),
        ),
    ]
