# Generated by Django 2.2.2 on 2020-04-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200401_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city_name',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='historicalcompany',
            old_name='city_name',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Country'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='is_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
