# Generated by Django 2.2.2 on 2020-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200420_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
