# Generated by Django 2.2.2 on 2019-11-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_historicalcompany_historicaljob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
