# Generated by Django 2.2.2 on 2019-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20191113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Actualizada', 'Actualizada'), ('', 'Sin cambios'), ('Inscripción cerrada', 'Inscripción cerrada')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('Actualizada', 'Actualizada'), ('', 'Sin cambios'), ('Inscripción cerrada', 'Inscripción cerrada')], default='', max_length=20, null=True),
        ),
    ]
