# Generated by Django 2.2.2 on 2020-04-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200423_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljob',
            old_name='summary',
            new_name='_summary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='_summary',
        ),
    ]
