# Generated by Django 2.2.2 on 2020-04-30 20:57

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200423_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Compañía', 'verbose_name_plural': 'Compañías'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Compañía'},
        ),
        migrations.AlterModelOptions(
            name='historicaljob',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Oferta de empleo'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Oferta de empleo', 'verbose_name_plural': 'Ofertas de empleo'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name', 'level'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.Province', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='community',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='area',
            field=django_mysql.models.ListCharField(models.CharField(max_length=45), blank=True, max_length=1570, null=True, size=34, verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.City', verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creción del registro'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_registered',
            field=models.BooleanField(blank=True, null=True, verbose_name='empresa colaboradora'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='offers',
            field=models.IntegerField(blank=True, null=True, verbose_name='nº de ofertas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reference',
            field=models.IntegerField(blank=True, null=True, verbose_name='nº de referencia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='resume',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='area',
            field=django_mysql.models.ListCharField(models.CharField(max_length=45), blank=True, max_length=1570, null=True, size=34, verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.City', verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de creción del registro'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='is_registered',
            field=models.BooleanField(blank=True, null=True, verbose_name='empresa colaboradora'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='offers',
            field=models.IntegerField(blank=True, null=True, verbose_name='nº de ofertas'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='reference',
            field=models.IntegerField(blank=True, null=True, verbose_name='nº de referencia'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='resume',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='area',
            field=models.CharField(choices=[('Educación, formación', 'Educación, formación'), ('Tecnología e informática', 'Tecnología e informática'), ('Sanidad, salud y servicios sociales', 'Sanidad, salud y servicios sociales'), ('Medios, editorial y artes gráficas', 'Medios, editorial y artes gráficas'), ('Compras, logística y transporte', 'Compras, logística y transporte'), ('Administrativos y secretariado', 'Administrativos y secretariado'), ('Profesionales, artes y oficios', 'Profesionales, artes y oficios'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Legal', 'Legal'), ('Internet', 'Internet'), ('Banca y seguros', 'Banca y seguros'), ('Calidad, I+D, PRL y medio ambiente', 'Calidad, I+D, PRL y medio ambiente'), ('Recursos humanos', 'Recursos humanos'), ('Comercial, ventas', 'Comercial, ventas'), ('Ingeniería y producción', 'Ingeniería y producción'), ('Atención al cliente', 'Atención al cliente'), ('Construcción e inmobiliaria', 'Construcción e inmobiliaria'), ('Hostelería, Turismo', 'Hostelería, Turismo'), ('Administración de Empresas', 'Administración de Empresas'), ('Marketing y comunicación', 'Marketing y comunicación')], max_length=40, verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20, null=True, verbose_name='categoría o nivel'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Company', verbose_name='compañía'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=40, verbose_name='tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de caducidad de la oferta'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='first_publication_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de publicación de la oferta'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='functions',
            field=models.TextField(blank=True, null=True, verbose_name='funciones'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='it_is_offered',
            field=models.TextField(blank=True, null=True, verbose_name='se ofrece'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='last_update_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de actualización de la oferta'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='maximum_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salario máximo'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='minimum_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salario míminimo'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='minimum_years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='experiencia mínima'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='nationality',
            field=models.CharField(max_length=30, verbose_name='nacionalidad'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.Province', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='recommendable_years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='experiencia recomendable'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='registered_people',
            field=models.PositiveIntegerField(default=0, verbose_name='inscritos'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='requisitos'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('', 'Sin cambios'), ('Actualizada', 'Actualizada'), ('Inscripción cerrada', 'Inscripción cerrada')], max_length=30, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='etiquetas'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='type',
            field=models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo nacional'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=30, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='vacancies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nº de vacantes'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'flexible'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=30, verbose_name='jornada laboral'),
        ),
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.CharField(choices=[('Educación, formación', 'Educación, formación'), ('Tecnología e informática', 'Tecnología e informática'), ('Sanidad, salud y servicios sociales', 'Sanidad, salud y servicios sociales'), ('Medios, editorial y artes gráficas', 'Medios, editorial y artes gráficas'), ('Compras, logística y transporte', 'Compras, logística y transporte'), ('Administrativos y secretariado', 'Administrativos y secretariado'), ('Profesionales, artes y oficios', 'Profesionales, artes y oficios'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Legal', 'Legal'), ('Internet', 'Internet'), ('Banca y seguros', 'Banca y seguros'), ('Calidad, I+D, PRL y medio ambiente', 'Calidad, I+D, PRL y medio ambiente'), ('Recursos humanos', 'Recursos humanos'), ('Comercial, ventas', 'Comercial, ventas'), ('Ingeniería y producción', 'Ingeniería y producción'), ('Atención al cliente', 'Atención al cliente'), ('Construcción e inmobiliaria', 'Construcción e inmobiliaria'), ('Hostelería, Turismo', 'Hostelería, Turismo'), ('Administración de Empresas', 'Administración de Empresas'), ('Marketing y comunicación', 'Marketing y comunicación')], max_length=40, verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20, null=True, verbose_name='categoría o nivel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='job.City', verbose_name='ciudades'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.Company', verbose_name='compañía'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=40, verbose_name='tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de caducidad de la oferta'),
        ),
        migrations.AlterField(
            model_name='job',
            name='first_publication_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de publicación de la oferta'),
        ),
        migrations.AlterField(
            model_name='job',
            name='functions',
            field=models.TextField(blank=True, null=True, verbose_name='funciones'),
        ),
        migrations.AlterField(
            model_name='job',
            name='it_is_offered',
            field=models.TextField(blank=True, null=True, verbose_name='se ofrece'),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='job.Language', verbose_name='idiomas'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_update_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fecha de actualización de la oferta'),
        ),
        migrations.AlterField(
            model_name='job',
            name='maximum_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salario máximo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salario míminimo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='experiencia mínima'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='job',
            name='nationality',
            field=models.CharField(max_length=30, verbose_name='nacionalidad'),
        ),
        migrations.AlterField(
            model_name='job',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.Province', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='job',
            name='recommendable_years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='experiencia recomendable'),
        ),
        migrations.AlterField(
            model_name='job',
            name='registered_people',
            field=models.PositiveIntegerField(default=0, verbose_name='inscritos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='requisitos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('', 'Sin cambios'), ('Actualizada', 'Actualizada'), ('Inscripción cerrada', 'Inscripción cerrada')], max_length=30, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='etiquetas'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo nacional'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=30, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualización del registro'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nº de vacantes'),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'flexible'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=30, verbose_name='jornada laboral'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('C2', 'C2'), ('C1', 'C1'), ('B2', 'B2'), ('B1', 'B1'), ('A2', 'A2'), ('A1', 'A1')], default='', max_length=2, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('inglés', 'inglés'), ('francés', 'francés'), ('alemán', 'alemán'), ('italiano', 'italiano'), ('ruso', 'ruso'), ('chino', 'chino'), ('japonés', 'japonés'), ('canadiense', 'canadiense'), ('portugués', 'portugués'), ('euskera', 'euskera'), ('catalán', 'catalán'), ('gallego', 'gallego'), ('vasco', 'vasco'), ('valenciano', 'valenciano'), ('castellano', 'castellano'), ('español', 'español'), ('danés', 'danés'), ('sueco', 'sueco'), ('suizo', 'suizo'), ('holandés', 'holandés'), ('noruego', 'noruego'), ('finés', 'finés'), ('lapón', 'lapón'), ('rumano', 'rumano'), ('polaco', 'polaco'), ('eslovaco', 'eslovaco'), ('checo', 'checo'), ('maltés', 'maltés'), ('árabe', 'árabe')], default='', max_length=15, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='province',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='job.Community', verbose_name='comunidad autónoma'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='job.Country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
    ]
