# Generated by Django 2.2.2 on 2019-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20191124_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'indiferente'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=23),
        ),
        migrations.AlterField(
            model_name='job',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'indiferente'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=23),
        ),
    ]
