# Generated by Django 2.2.2 on 2019-11-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20191126_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='area',
            field=models.CharField(choices=[('Educación, formación', 'Educación, formación'), ('Tecnología e informática', 'Tecnología e informática'), ('Sanidad, salud y servicios sociales', 'Sanidad, salud y servicios sociales'), ('Medios, editorial y artes gráficas', 'Medios, editorial y artes gráficas'), ('Compras, logística y transporte', 'Compras, logística y transporte'), ('Administrativos y secretariado', 'Administrativos y secretariado'), ('Profesionales, artes y oficios', 'Profesionales, artes y oficios'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Legal', 'Legal'), ('Internet', 'Internet'), ('Banca y seguros', 'Banca y seguros'), ('Calidad, I+D, PRL y medio ambiente', 'Calidad, I+D, PRL y medio ambiente'), ('Recursos humanos', 'Recursos humanos'), ('Comercial, ventas', 'Comercial, ventas'), ('Ingeniería y producción', 'Ingeniería y producción'), ('Atención al cliente', 'Atención al cliente'), ('Construcción e inmobiliaria', 'Construcción e inmobiliaria'), ('Hostelería, Turismo', 'Hostelería, Turismo'), ('Administración de Empresas', 'Administración de Empresas'), ('Marketing y comunicación', 'Marketing y comunicación')], max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('', 'Sin cambios'), ('Actualizada', 'Actualizada'), ('Inscripción cerrada', 'Inscripción cerrada')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='type',
            field=models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo nacional'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'indiferente'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.CharField(choices=[('Educación, formación', 'Educación, formación'), ('Tecnología e informática', 'Tecnología e informática'), ('Sanidad, salud y servicios sociales', 'Sanidad, salud y servicios sociales'), ('Medios, editorial y artes gráficas', 'Medios, editorial y artes gráficas'), ('Compras, logística y transporte', 'Compras, logística y transporte'), ('Administrativos y secretariado', 'Administrativos y secretariado'), ('Profesionales, artes y oficios', 'Profesionales, artes y oficios'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Legal', 'Legal'), ('Internet', 'Internet'), ('Banca y seguros', 'Banca y seguros'), ('Calidad, I+D, PRL y medio ambiente', 'Calidad, I+D, PRL y medio ambiente'), ('Recursos humanos', 'Recursos humanos'), ('Comercial, ventas', 'Comercial, ventas'), ('Ingeniería y producción', 'Ingeniería y producción'), ('Atención al cliente', 'Atención al cliente'), ('Construcción e inmobiliaria', 'Construcción e inmobiliaria'), ('Hostelería, Turismo', 'Hostelería, Turismo'), ('Administración de Empresas', 'Administración de Empresas'), ('Marketing y comunicación', 'Marketing y comunicación')], max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='category_level',
            field=models.CharField(choices=[('Mandos', 'Mandos'), ('Empleados', 'Empleados'), ('Técnicos', 'Técnicos'), ('Dirección', 'Dirección'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract',
            field=models.CharField(choices=[('Contrato sin especificar', 'sin especificar'), ('Contrato Prácticas', 'prácticas'), ('Contrato Indefinido', 'indefinido'), ('Contrato Autónomo o freelance', 'autónomo o freelance'), ('Contrato Fijo discontinuo', 'fijo discontinuo'), ('Contrato Formativo', 'formativo'), ('Contrato De duración determinada', 'de duración determinada')], default='Contrato sin especificar', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('', 'Sin cambios'), ('Actualizada', 'Actualizada'), ('Inscripción cerrada', 'Inscripción cerrada')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo nacional'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_day',
            field=models.CharField(choices=[('Jornada sin especificar', 'sin especificar'), ('Jornada Intensiva', 'intensiva'), ('Jornada Indiferente', 'indiferente'), ('Jornada Parcial', 'parcial'), ('Jornada Fin de Semana', 'fin de semana'), ('Jornada Completa', 'completa'), ('Jornada Tele Trabajo', 'tele trabajo')], default='Sin especificar', max_length=30),
        ),
    ]
