# Generated by Django 2.2.2 on 2019-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20191127_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='_contract',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='_working_day',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='_contract',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='_working_day',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
