FROM python:3.7

RUN mkdir -p /IE/src
WORKDIR /IE/src
ADD . /IE/src/

ENV PYTHONUNBUFFERED 1
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install --yes --no-install-recommends apt-utils
RUN pip install --upgrade pip
RUN apt-get -q update && apt-get -qy install netcat
RUN apt-get install dos2unix
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --no-input --clear

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
# https://github.com/ufoscout/docker-compose-wait/blob/master/LICENSE
RUN chmod +x /wait

RUN chmod +x /IE/src/entrypoint.sh
RUN dos2unix /IE/src/entrypoint.sh
ENTRYPOINT ["/IE/src/entrypoint.sh"]