# Generated by Django 2.2.2 on 2019-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='x',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y',
            field=models.IntegerField(default=25),
        ),
    ]
