# Generated by Django 2.2.2 on 2019-07-02 10:40

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('capital_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_link', models.URLField(null=True)),
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_description', models.TextField(null=True)),
                ('company_city_name', models.CharField(max_length=50)),
                ('company_category', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('company_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='jobs.City')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpiderState',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('last_page', models.IntegerField(default=1, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('default_results_showed', models.IntegerField(default=20)),
                ('results_count', models.IntegerField(default=0, null=True)),
                ('last_result_parsed', models.IntegerField(default=0, null=True)),
                ('last_page_parsed', models.IntegerField(default=0, null=True)),
                ('scrapping_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('community_number', models.IntegerField(blank=True, null=True)),
                ('capital_id', models.IntegerField(null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='jobs.Community')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='jobs.Country')),
            ],
            options={
                'verbose_name': 'Province',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('type', models.CharField(choices=[('ofertas-internacionales', 'Empleo internacional'), ('trabajo', 'Empleo'), ('primer-empleo', 'Primer empleo')], default='trabajo', max_length=23)),
                ('summary', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, null=True, size=6)),
                ('_experience', models.CharField(blank=True, max_length=30, null=True)),
                ('_salary', models.CharField(blank=True, max_length=30, null=True)),
                ('_contract', models.CharField(blank=True, max_length=30, null=True)),
                ('_working_day', models.CharField(blank=True, max_length=30, null=True)),
                ('minimum_years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('recommendable_years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('minimum_salary', models.IntegerField(blank=True, null=True)),
                ('maximum_salary', models.IntegerField(blank=True, null=True)),
                ('working_day', models.CharField(blank=True, max_length=30, null=True)),
                ('contract', models.CharField(blank=True, max_length=30, null=True)),
                ('city_name', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, null=True, size=6)),
                ('province_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_name', models.CharField(max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30)),
                ('registered_people', models.IntegerField()),
                ('job_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('it_is_offered', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('category_level', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancies', models.IntegerField()),
                ('vacancies_update', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cities', models.ManyToManyField(blank=True, null=True, related_name='jobs', to='jobs.City')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Country')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Province')),
            ],
            options={
                'verbose_name': 'Job',
                'ordering': ['-created_at', 'job_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='jobs.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='jobs.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='jobs.Province'),
        ),
    ]
