# Generated by Django 2.2.2 on 2019-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
