# Generated by Django 2.2.2 on 2019-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190702_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_city_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
